from typing import Protocol, List, Optional, Dict, Any, Callable
from core.state import TrackInfo

class AudioPlayerPort(Protocol):
    is_connected: bool

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def play(self, uri: str) -> None: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def stop(self) -> None: ...
    async def set_volume(self, volume: int) -> None: ...
    async def seek(self, position: float) -> None: ...


class MediaExtractorPort(Protocol):
    async def search(self, query: str, max_results: int = 15) -> List[TrackInfo]: ...
    async def extract_info(self, url: str) -> Optional[TrackInfo]: ...
    async def get_stream_url(self, video_id: str) -> Optional[str]: ...
    async def download_mp3(self, video_id: str, on_progress: Optional[Callable] = None) -> str: ...
    def cancel_download(self) -> None: ...


class TrackRepositoryPort(Protocol):
    async def upsert_track(self, track: TrackInfo, stream_url: Optional[str] = None, local_path: Optional[str] = None) -> None: ...
    async def update_stream_url_only(self, video_id: str, stream_url: str) -> None: ...
    async def get_track(self, video_id: str) -> Optional[TrackInfo]: ...
    async def increment_play_count(self, video_id: str) -> None: ...

class SessionRepositoryPort(Protocol):
    async def create_session(self, token: str, expires_at: int) -> None: ...
    async def verify_session(self, token: str) -> bool: ...
    async def delete_session(self, token: str) -> None: ...
    async def cleanup_sessions(self) -> None: ...

class DatabasePort(TrackRepositoryPort, SessionRepositoryPort, Protocol):
    async def init(self) -> None: ...
    async def close(self) -> None: ...
